spring:
  devtools:
    livereload:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

  datasource:
    url: jdbc:mysql://localhost:3306/uknowtodo?characterEncoding=UTF-8&serverTimezone=UTC
    username: todo
    password: todo123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate: debug
